apiVersion: v1
kind: Pod
metadata:
  name: rdma-vf-ping-a
  labels:
    app: rdma-vf-pingpong
  annotations:
    k8s.v1.cni.cncf.io/networks: rdma-vf
spec:
  restartPolicy: Never
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                  - BM.GPU.B4.8
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: rdma-vf-pingpong
          topologyKey: kubernetes.io/hostname
  volumes:
    - name: devinf
      hostPath:
        path: /dev/infiniband
  containers:
    - name: pingpong
      image: iad.ocir.io/idxzjcdglx2s/nccl-tests:cuda-13.1.1-ubuntu-24.04-nccl-2.29.3-020926.1
      command: ["bash", "-c", "trap : TERM INT; sleep infinity & wait"]
      securityContext:
        privileged: true
        capabilities:
          add: ["IPC_LOCK"]
      volumeMounts:
        - name: devinf
          mountPath: /dev/infiniband
      resources:
        limits:
          nvidia.com/rdma-vf: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: rdma-vf-ping-b
  labels:
    app: rdma-vf-pingpong
  annotations:
    k8s.v1.cni.cncf.io/networks: rdma-vf
spec:
  restartPolicy: Never
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                  - BM.GPU.B4.8
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: rdma-vf-pingpong
          topologyKey: kubernetes.io/hostname
  volumes:
    - name: devinf
      hostPath:
        path: /dev/infiniband
  containers:
    - name: pingpong
      image: iad.ocir.io/idxzjcdglx2s/nccl-tests:cuda-13.1.1-ubuntu-24.04-nccl-2.29.3-020926.1
      command: ["bash", "-c", "trap : TERM INT; sleep infinity & wait"]
      securityContext:
        privileged: true
        capabilities:
          add: ["IPC_LOCK"]
      volumeMounts:
        - name: devinf
          mountPath: /dev/infiniband
      resources:
        limits:
          nvidia.com/rdma-vf: 1
